# Generated by Django 4.2.6 on 2023-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="telefone",
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
