# Generated by Django 4.2.5 on 2023-09-26 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saida', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
